development:
  adapter: postgresql
  encoding: unicode
  database: meeting_room_booking_development
  pool: 5
  username: mike
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meeting_room_booking_tests
  pool: 5
  username: sample_postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: meeting_room_booking
  pool: 5
  username: sample_postgres
  password:
